# Site settings
title: TuTu生活志
name: tutulifestyle # your name
email: tutulifestyle.com@gmail.com # your email address
description: >
    TuTulifestyle backup website # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "tutulifestyle.github.io" # the base hostname & protocol for your site
twitter_username: tutulifestyle # your Twitter username
github_username: tutulifestyle # your Github username
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
